name = "DGGS"
uuid = "1b1208a4-f9dd-4606-8704-9f68bba98fd1"
authors = ["Daniel Loos"]
version = "2.0.0-DEV"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DiskArrayTools = "fcd2136c-9f69-4db6-97e5-f31981721d63"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"

[extensions]
DGGSMakie = "Makie"
DGGSZarr = "Zarr"

[compat]
CoordinateTransformations = "0.6.4"
DiskArrayTools = "0.1.12"
Extents = "0.1.5"
GeometryBasics = "0.5.9"
Infiltrator = "1.8.8"
OrderedCollections = "1.8.1"
StaticArrays = "1.9.13"
YAXArrays = "0.6.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
